# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  install:
    cmds:
      - helm repo add crossplane-stable https://charts.crossplane.io/stable && helm repo update
      - helm install crossplane \
        --namespace crossplane-system \
        --create-namespace crossplane-stable/crossplane
      - kubectl get pods -n crossplane-system
      - kubectl get deployments -n crossplane-system
#      - helm install crossplane \
#        --namespace crossplane-system \
#        --create-namespace crossplane-stable/crossplane \
#        --version 1.10.0

