[workspace]
members = [
    "apps/rust/users-redis",
    "apps/rust/users-grpc",
    "libs/rust/grpc",
    "libs/rust/graphql/starwars",
    "libs/rust/mongo",
    "apps/rust/api-graphql",
    "apps/rust/api-rest"
]
