# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  up:
    cmds:
      - ctlptl create cluster k3d --name=k3d-pod-cluster --registry=ctlptl-registry
      - helm install kube-prometheus bitnami/kube-prometheus -n prometheus --create-namespace --set installCRDs=true
      - ctlptl create cluster k3d --name=k3d-dev-cluster --registry=ctlptl-registry
      - helm install kube-prometheus bitnami/kube-prometheus -n prometheus --create-namespace --set installCRDs=true
      - kubectl create namespace argocd
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl wait --for condition=Available=True --timeout=300s deployment/argocd-server --namespace argocd
      - kubectl apply -f k8s/argocd/apps.yaml
#      - istioctl install --set profile=default --verify -y # change this to helm
#      - kubectl label namespace default istio-injection=enabled
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.15/samples/bookinfo/platform/kube/bookinfo.yaml --wait
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.15/samples/bookinfo/networking/bookinfo-gateway.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/addons/prometheus.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/addons/grafana.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/addons/kiali.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/addons/jaeger.yaml
      - kubeshark tap &
#      - just install-linkerd
#      - just install-viz
      - tilt up
#      - open argocd ui
  get-secret:
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  down:
    cmds:
      - kubeshark clean
      - tilt down
      - ctlptl delete cluster k3d-pod-cluster
      - ctlptl delete cluster k3d-dev-cluster
