apiVersion: v1
kind: Namespace
metadata:
  name: users
spec: {}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  annotations:
    annotations: annotation1
  labels:
    account: users-client
  name: users-sa
  namespace: users
---
apiVersion: v1
kind: ConfigMap
data:
  stam: my data here
immutable: false
metadata:
  annotations:
    annotation1: annotation1
    annotation2: annotation2
  name: nginx-config
  namespace: users
---
apiVersion: v1
kind: Service
metadata:
  name: default-name-service
  namespace: users
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cdk8s-example-api-c8595c9a
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-name
  namespace: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdk8s-example-api-c8595c9a
  template:
    metadata:
      labels:
        app: cdk8s-example-api-c8595c9a
    spec:
      containers:
        - image: nginx
          name: app
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: default-name-service
  namespace: users
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: cdk8s-example-web-c8c271ec
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-name
  namespace: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdk8s-example-web-c8c271ec
  template:
    metadata:
      labels:
        app: cdk8s-example-web-c8c271ec
    spec:
      containers:
        - image: nginx
          name: app
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: nginx-config
