apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-nest-app
  labels:
    app: deno-nest-app
    version: v1
spec:
  replicas: 1

  template:
    metadata:
      name: deno-nest-app
      labels:
        app: deno-nest-app
        version: v1
      annotations:
        "linkerd.io/inject": "enabled"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "deno-nest-app"
        "consul.hashicorp.com/connect-service-protocol": "http"
        "consul.hashicorp.com/service-meta-version": "v.1.1"
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
    spec:
      serviceAccountName: deno-nest-app
      containers:
        - name: deno-nest-app
          image: yurikrupnik/deno-nest-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb+srv://yurikrupnik:T4eXKj1RBI4VnszC@cluster0.rdmew.mongodb.net/

      restartPolicy: Always
  selector:
    matchLabels:
      app: deno-nest-app
      version: v1
