# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo from Platform "{{.GREETING}}"
    silent: true
  kind-local-cluster:
    #    dir: '{{.USER_WORKING_DIR}}'
    desc: Create kind 4 cores local cluster.
    aliases:
      - kind:up
    dir: platform
    summary: Create Kind Cluster
    preconditions:
      - test -f cluster.yaml
    cmds:
#      - cat cluster.yaml
#      - TODO! chabge back to cluster
      - kind create cluster --name simulate-staging1 --config cluster.yaml
  k3d-local-cluster:
    desc: Create k3d single core local cluster.
    #    dir: '{{.USER_WORKING_DIR}}'
    dir: platform
    summary: |
      Release your project to github

      It will build your project before starting the release.
      Please make sure that you have set GITHUB_TOKEN before starting.
#    preconditions:
#      - test -f cluster.yaml
    cmds:
      - ctlptl create cluster k3d --name=k3d-simulate-dev1 --registry=ctlptl-registry
