version: '3'

vars:
  GREETING: Hello from k8s
  STATIC: static
  DYNAMIC:
    sh: echo "dynamic"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - deno run --allow-all main.ta
    silent: true
  kind-local-cluster:
#    dir: '{{.USER_WORKING_DIR}}'
    dir: k8s
    summary: Create Kind Cluster
    preconditions:
      - test -f cluster.yaml
    cmds:
      - kind create cluster --name my-cluster --config cluster.yaml
#      - ls
#      - ctlptl create cluster kind --name=kind-prod-cluster --registry=ctlptl-registry
#      - ctlptl create cluster k3d --name=k3d-prod-cluster --registry=ctlptl-registry
  up:
#    dir: '{{.USER_WORKING_DIR}}'
    deps:
      - kind-local-cluster
    preconditions:
      - test -f Tiltfile
    cmds:
      - cat Tiltfile
      - deno run --allow-all main.ts
      - cargo run
#      - cat WORKSPACE
