apiVersion: v1
kind: Service
metadata:
  name: frontend-host-service
  labels:
    run: frontend-host-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: frontend-host
