// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema EventBus
 */
export class EventBus extends ApiObject {
  /**
   * Returns the apiVersion and kind for "EventBus"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'argoproj.io/v1alpha1',
    kind: 'EventBus',
  }

  /**
   * Renders a Kubernetes manifest for "EventBus".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: EventBusProps): any {
    return {
      ...EventBus.GVK,
      ...toJson_EventBusProps(props),
    };
  }

  /**
   * Defines a "EventBus" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: EventBusProps) {
    super(scope, id, {
      ...EventBus.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...EventBus.GVK,
      ...toJson_EventBusProps(resolved),
    };
  }
}

/**
 * @schema EventBus
 */
export interface EventBusProps {
  /**
   * @schema EventBus#metadata
   */
  readonly metadata: ApiObjectMetadata;

  /**
   * @schema EventBus#spec
   */
  readonly spec: any;

}

/**
 * Converts an object of type 'EventBusProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_EventBusProps(obj: EventBusProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': obj.spec,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema EventSource
 */
export class EventSource extends ApiObject {
  /**
   * Returns the apiVersion and kind for "EventSource"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'argoproj.io/v1alpha1',
    kind: 'EventSource',
  }

  /**
   * Renders a Kubernetes manifest for "EventSource".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: EventSourceProps): any {
    return {
      ...EventSource.GVK,
      ...toJson_EventSourceProps(props),
    };
  }

  /**
   * Defines a "EventSource" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: EventSourceProps) {
    super(scope, id, {
      ...EventSource.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...EventSource.GVK,
      ...toJson_EventSourceProps(resolved),
    };
  }
}

/**
 * @schema EventSource
 */
export interface EventSourceProps {
  /**
   * @schema EventSource#metadata
   */
  readonly metadata: ApiObjectMetadata;

  /**
   * @schema EventSource#spec
   */
  readonly spec: any;

}

/**
 * Converts an object of type 'EventSourceProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_EventSourceProps(obj: EventSourceProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': obj.spec,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema Sensor
 */
export class Sensor extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Sensor"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'argoproj.io/v1alpha1',
    kind: 'Sensor',
  }

  /**
   * Renders a Kubernetes manifest for "Sensor".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: SensorProps): any {
    return {
      ...Sensor.GVK,
      ...toJson_SensorProps(props),
    };
  }

  /**
   * Defines a "Sensor" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: SensorProps) {
    super(scope, id, {
      ...Sensor.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...Sensor.GVK,
      ...toJson_SensorProps(resolved),
    };
  }
}

/**
 * @schema Sensor
 */
export interface SensorProps {
  /**
   * @schema Sensor#metadata
   */
  readonly metadata: ApiObjectMetadata;

  /**
   * @schema Sensor#spec
   */
  readonly spec: any;

}

/**
 * Converts an object of type 'SensorProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_SensorProps(obj: SensorProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': obj.spec,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

