#load("//:my_custom_rule.bzl", "write_new_file")

#write_new_file(
#  name = "write_my_custom_message_into_file",
#  my_input_file = "//:a.txt",
#  out_file_name = "my_awesome_output"
#)
#load("@io_bazel_rules_go//go:def.bzl", "go_binary")
#gazelle(name = "gazelle")
#go_binary(
#    name = "",
#    srcs = ["./main.go"],
##    visibility = ["//visibility:public"],
#)
