#load("//:my_custom_rule.bzl", "write_new_file")

#write_new_file(
#  name = "write_my_custom_message_into_file",
#  my_input_file = "//:a.txt",
#  out_file_name = "my_awesome_output"
#)
load("@io_bazel_rules_go//go:def.bzl", "go_binary")
#gazelle(name = "gazelle")
#go_binary(
#    name = "",
#    srcs = ["./main.go"],
##    visibility = ["//visibility:public"],
#)
#load("@io_bazel_rules_k8s//k8s:object.bzl", "k8s_object")

#k8s_object(
#  name = "dev",
#  kind = "deployment",
#
#  # A template of a Kubernetes Deployment object yaml.
#  template = ":deployment.yaml",
#
#  # An optional collection of docker_build images to publish
#  # when this target is bazel run.  The digest of the published
#  # image is substituted as a part of the resolution process.
#  images = {
#    "gcr.io/rules_k8s/server:dev": "//server:image"
#  },
#)
#
#k8s_object(
#  name = "snack-server",
#  kind = "deployment",
#
#  template = ":deploy/snack.yaml",
#
#  cluster = "docker-for-desktop-cluster",
#)
